[project]
name = "yourbench"
version = "0.1.0"
description = "Dynamic Evaluation Set Generation with LLMs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.2.0",
    "litellm>=1.55.12",
    "loguru>=0.7.3",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.8.4",
]

[project.scripts]
yourbench = "yourbench.main:main"

# Code style
[tool.ruff]
line-length = 119

# Move these settings directly under [tool.ruff]
ignore = ["E501"]
select = ["C", "E", "F", "I", "W"]
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
preview = true

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["yourbench"]

[tool.ruff.format]
quote-style = "double" # Like Black, use double quotes for strings.
indent-style = "space" # Like Black, indent with spaces, rather than tabs.
skip-magic-trailing-comma = false # Like Black, respect magic trailing commas.
line-ending = "auto" # Like Black, automatically detect the appropriate line ending.

[tool.setuptools.packages.find]
where = ["src"]
