[project]
name = "yourbench"
version = "0.1.0"
description = "Dynamic Evaluation Set Generation with LLMs"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "async-timeout>=5.0.1",
    "asyncio>=3.4.3",
    "datasets>=3.2.0",
    "faiss-cpu>=1.9.0.post1",
    "hf-transfer>=0.1.8",
    "kneed>=0.8.5",
    "langfuse>=2.57.1",
    "litellm>=1.55.12",
    "loguru>=0.7.3",
    "matplotlib>=3.10.0",
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "ruff>=0.8.4",
    "scikit-learn>=1.6.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=3.3.1",
    "tqdm>=4.67.1",
    "transformers>=4.48.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "platform_system != 'Linux'" },
  { index = "pytorch-cu124", marker = "platform_system == 'Linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "platform_system != 'Linux'" },
  { index = "pytorch-cu124", marker = "platform_system == 'Linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv]
package = true

[project.scripts]
yourbench = "yourbench.main:main"

# Code style
[tool.ruff]
line-length = 119

# Move these settings directly under [tool.ruff]
lint.ignore = ["E501"]
lint.select = ["C", "E", "F", "I", "W"]
lint.fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
preview = true

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["yourbench"]

[tool.ruff.format]
quote-style = "double" # Like Black, use double quotes for strings.
indent-style = "space" # Like Black, indent with spaces, rather than tabs.
skip-magic-trailing-comma = false # Like Black, respect magic trailing commas.
line-ending = "auto" # Like Black, automatically detect the appropriate line ending.

[tool.setuptools.packages.find]
where = ["yourbench"]
