[project]
name = "yourbench"
version = "0.1.0"
description = "A dynamic evaluation set generation tool for LLMs"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=23.2.1",
    "aiohttp>=3.10.10",
    "anthropic>=0.37.1",
    "async-timeout>=4.0.3",
    "datasets>=3.0.2",
    "huggingface-hub>=0.26.1",
    "langfuse>=2.55.0",
    "litellm>=1.51.0",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "openai>=1.52.2",
    "pandas>=2.2.3",
    "pydantic>=2.9.2",
    "PyYAML>=6.0.1",
    "scikit-learn>=1.5.2",
    "sentence-transformers>=3.2.1",
    "torch>=2.4.0",
    "tqdm>=4.66.5",
    "transformers>=4.46.0"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.8.1",
    "pytest>=7.0.0"
]

# Code style
[tool.ruff]
line-length = 119

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# Never enforce `E501` (line length violations).
ignore = ["E501"]
select = ["C", "E", "F", "I", "W"]
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
preview = true

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["lighteval"]

[tool.ruff.format]
quote-style = "double" # Like Black, use double quotes for strings.
indent-style = "space" # Like Black, indent with spaces, rather than tabs.
skip-magic-trailing-comma = false # Like Black, respect magic trailing commas.
line-ending = "auto" # Like Black, automatically detect the appropriate line ending.

[tool.setuptools.packages.find]
where = ["src"]