# === HUGGINGFACE SETTINGS CONFIGURATION ===
hf_configuration:
  token: $HF_TOKEN # you can get one from here!: https://huggingface.co/docs/huggingface_hub/en/quick-start#authentication
  hf_organization: $HF_ORGANIZATION # defaults to your HF username. You can set it to your organization name.
  private: false # true by default, set to false to make the dataset public
  global_dataset_name: sumuks/yourbench-example # name of the dataset to save the traces, and generated questions to.

# === MODEL CONFIGURATION ===
model_list: 
  # to use the default huggingface inference
  - model_name: Qwen/Qwen2.5-72B-Instruct
    api_key: $HF_TOKEN
    inference_backend: hf_hub
  
  # to use openai inference
  - model_name: gpt-4o-mini
    api_key: $OPENAI_API_KEY

  # to use anthropic inference
  - model_name: claude-3-7-sonnet-20250219
    request_style: anthropic
    api_key: $ANTHROPIC_API_KEY
  
  # to use deepseek inference
  - model_name: deepseek-chat
    request_style: openai
    base_url: $DEEPSEEK_API_BASE
    api_key: $DEEPSEEK_API_KEY
  
  # to use local inference with vLLM
  - model_name: your_model_here
    base_url: http://localhost:8000/v1
    max_concurrent_requests: 128 # optional, defaults to 8
    


model_roles:
  ingestion:
    - Qwen/Qwen2.5-72B-Instruct # you must use a vision supported model for ingestion
  summarization:
    - Qwen/Qwen2.5-72B-Instruct
  chunking:
    - intfloat/multilingual-e5-large-instruct # your sentence level chunking model
  single_shot_question_generation:
    - Qwen/Qwen2.5-72B-Instruct
  multi_hop_question_generation:
    - Qwen/Qwen2.5-72B-Instruct

pipeline:
  ingestion:
    run: true
    source_documents_dir: data/example/raw
    output_dir: data/example/processed
  
  upload_ingest_to_hub:
    run: true
    source_documents_dir: data/example/processed
    output_subset: ingested_documents

  summarization:
    run: true
    source_subset: ingested_documents
    output_subset: summarized_documents
  
  chunking:
    run: true
    source_subset: summarized_documents
    output_subset: chunked_documents
    
    chunking_configuration:
      l_min_tokens: 64
      l_max_tokens: 128
      tau_threshold: 0.8
      h_min: 2
      h_max: 5
      num_multihops_factor: 2   # or any integer or float
  
  single_shot_question_generation:
    run: true
    concat_existing_dataset: true
    source_subset: chunked_documents
    output_subset: single_shot_questions
    additional_instructions: "Generate questions to test a curious adult"
    # for cost reduction
    chunk_sampling:
      mode: "count" # or "all" for all chunks
      value: 5
      random_seed: 123
  
  multi_hop_question_generation:
    run: true
    concat_existing_dataset: true
    source_subset: chunked_documents
    output_subset: multi_hop_questions
    additional_instructions: "Generate questions to test a curious adult"
    # for cost reduction
    chunk_sampling:
      mode: "percentage" # or "count" for a fixed number
      value: 0.3
      random_seed: 42

  lighteval:
    run: true
  
  
