task_name: agriculture
datasets:
  # where your text or markdown files are stored
  source_directory: examples/agriculture
  document_dataset_name: sumuks/yourbench_agriculture
  # if both the names are the same, we'll attempt to push back to the original dataset
  document_with_summary_dataset_name: sumuks/yourbench_agriculture
  chunked_doucments_dataset_name: sumuks/yourbench_agriculture_semantically_chunked
  multihop_pairings_dataset_name: sumuks/yourbench_agriculture_multihop_pairings
  single_shot_questions_dataset_name: sumuks/yourbench_agriculture_single_shot_questions_llama
  multihop_questions_dataset_name: sumuks/yourbench_agriculture_multihop_questions_gpt4omini_v2
chunking_configuration:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  min_tokens: 256 # tokens
  target_chunk_size: 512 # tokens
  max_tokens: 1024 # tokens
  similarity_threshold: 0.3
  device: cuda # if you have a GPU, you can use it here or set to cpu
question_generation_config:
  prompt_prefix: simple_qg
  # test_audience: "5th grader, with longer attention span, and longer answers"
  test_audience: "phd"
pipeline_config:
  # - generate_dataset
  # - generate_summaries
  # - create_chunks
  # - make_multihop_chunks
  # - create_single_shot_questions
  - create_multihop_questions
prompt_prefix: general
model_config:
  model_index: 1
  # models are prioritized by the order they are defined in the config
  summarization_model:
    model_name: gpt-4o
    model_type: azure
    # model_name: claude-3-5-sonnet-20241022
    # model_name: claude-3-haiku-20240307
    # model_type: anthropic
  model_0:
    model_name: meta-llama/Meta-Llama-3.3-70B-Instruct
    model_type: openai
    base_url: http://localhost:30000/v1/
    api_key: "EMPTY"
  model_1:
    model_name: gpt-4o-mini
    model_type: azure